export const VALIDATION_CONSTRAINTS = {
  ACCOUNT_NAME_MIN_LENGTH: 1,
  ACCOUNT_NAME_MAX_LENGTH: 100,
  USERNAME_MIN_LENGTH: 3,
  USERNAME_MAX_LENGTH: 30,
  PASSWORD_MIN_LENGTH: 1,
  PASSWORD_MAX_LENGTH: 12,
  NAME_MIN_LENGTH: 1,
  NAME_MAX_LENGTH: 100,
  MIN_AGE: 13,
  VEHICLE_LICENSE_PLATE_MIN_LENGTH: 4,
  VEHICLE_LICENSE_PLATE_MAX_LENGTH: 20,
  VEHICLE_BRAND_MIN_LENGTH: 1,
  VEHICLE_BRAND_MAX_LENGTH: 50,
  VEHICLE_MODEL_MIN_LENGTH: 1,
  VEHICLE_MODEL_MAX_LENGTH: 50,
  VEHICLE_BATTERY_CAPACITY_MIN: 10,
  VEHICLE_BATTERY_CAPACITY_MAX: 500,
  TRANSACTION_MIN_TOP_UP: 1000,
  TRANSACTION_DEBT_LIMIT: -50000,
} as const

export const VALIDATION_MESSAGES = {
  ACCOUNT_NAME_REQUIRED: 'Account name is required',
  ACCOUNT_NAME_MAX_LENGTH: `Account name length exceeded ${VALIDATION_CONSTRAINTS.ACCOUNT_NAME_MAX_LENGTH} characters`,
  ACCOUNT_NAME_INVALID_FORMAT:
    'Enter a valid email or username (letters, numbers, underscores only)',
  PASSWORD_REQUIRED: 'Password is required',
  PASSWORD_MAX_LENGTH: `Password length exceeded ${VALIDATION_CONSTRAINTS.PASSWORD_MAX_LENGTH} characters`,
  EMAIL_REQUIRED: 'Email is required',
  EMAIL_INVALID: 'Enter a valid email address',
  EMAIL_ALREADY_EXISTS: 'This email is already registered',
  USERNAME_ALREADY_EXISTS: 'This username is already taken',
  USERNAME_REQUIRED: 'Username is required',
  USERNAME_MIN_LENGTH: `Username must be at least ${VALIDATION_CONSTRAINTS.USERNAME_MIN_LENGTH} characters`,
  USERNAME_MAX_LENGTH: `Username length exceeded ${VALIDATION_CONSTRAINTS.USERNAME_MAX_LENGTH} characters`,
  USERNAME_INVALID_FORMAT:
    'Username can only contain letters, numbers, and underscores',
  NAME_REQUIRED: 'Name is required',
  NAME_MAX_LENGTH: `Name length exceeded ${VALIDATION_CONSTRAINTS.NAME_MAX_LENGTH} characters`,
  DOB_REQUIRED: 'Date of birth is required',
  DOB_INVALID: 'Enter a valid date of birth',
  DOB_MIN_AGE: `You must be at least ${VALIDATION_CONSTRAINTS.MIN_AGE} years old`,
  VEHICLE_LICENSE_PLATE_REQUIRED: 'License plate is required',
  VEHICLE_LICENSE_PLATE_MIN_LENGTH: `License plate must be at least ${VALIDATION_CONSTRAINTS.VEHICLE_LICENSE_PLATE_MIN_LENGTH} characters`,
  VEHICLE_LICENSE_PLATE_MAX_LENGTH: `License plate must be at most ${VALIDATION_CONSTRAINTS.VEHICLE_LICENSE_PLATE_MAX_LENGTH} characters`,
  VEHICLE_BRAND_REQUIRED: 'Brand is required',
  VEHICLE_MODEL_REQUIRED: 'Model is required',
  VEHICLE_BATTERY_CAPACITY_REQUIRED: 'Battery capacity is required',
  VEHICLE_BATTERY_CAPACITY_MIN: `Battery capacity must be at least ${VALIDATION_CONSTRAINTS.VEHICLE_BATTERY_CAPACITY_MIN} kWh`,
  VEHICLE_BATTERY_CAPACITY_MAX: `Battery capacity must be at most ${VALIDATION_CONSTRAINTS.VEHICLE_BATTERY_CAPACITY_MAX} kWh`,
  TRANSACTION_MIN_TOP_UP: `Minimum top-up is ${VALIDATION_CONSTRAINTS.TRANSACTION_MIN_TOP_UP / 100} credits`,
  TRANSACTION_AMOUNT_POSITIVE: 'Amount must be positive',
  TRANSACTION_DEBT_REPAYMENT_EXCEEDS: 'Repayment amount exceeds current debt',
  TRANSACTION_NOT_IN_DEBT: 'You are not in debt',
  STATION_NOT_AVAILABLE: 'Station is not available',
  VEHICLE_NOT_OWNED: 'Vehicle does not belong to you',
  SESSION_ACTIVE: 'You already have an active charging session',
  SESSION_INSUFFICIENT_CREDITS: 'Insufficient credits. Please top up first.',
  USER_LOCKED: 'Your account has been locked',
  CANNOT_LOCK_ADMIN: 'Cannot lock admin accounts',
  USER_ID_REQUIRED: 'User ID is required',
  BATTERY_CAPACITY_WHOLE_NUMBER: 'Battery capacity must be a whole number',
  TRANSACTION_AMOUNT_WHOLE_NUMBER: 'Amount must be a whole number',
} as const
